export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_INFORMATION_REQUEST = 'ORDER_INFORMATION_REQUEST';
export const ORDER_INFORMATION_SUCCESS = 'ORDER_INFORMATION_SUCCESS';
export const ORDER_INFORMATION_FAIL = 'ORDER_INFORMATION_FAIL';

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST';
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS';
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL';
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET';

export const ORDER_HISTORY_REQUEST = 'ORDER_HISTORY_REQUEST';
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_FAIL = 'ORDER_HISTORY_FAIL';
export const ORDER_HISTORY_RESET = 'ORDER_HISTORY_RESET';

export const ORDER_ALL_REQUEST = 'ORDER_ALL_REQUEST';
export const ORDER_ALL_SUCCESS = 'ORDER_ALL_SUCCESS';
export const ORDER_ALL_FAIL = 'ORDER_ALL_FAIL';

export const ORDER_DELIVERY_STATUS_REQUEST = 'ORDER_DELIVERY_STATUS_REQUEST';
export const ORDER_DELIVERY_STATUS_SUCCESS = 'ORDER_DELIVERY_STATUS_SUCCESS';
export const ORDER_DELIVERY_STATUS_FAIL = 'ORDER_DELIVERY_STATUS_FAIL';
export const ORDER_DELIVERY_STATUS_RESET = 'ORDER_DELIVERY_STATUS_RESET';
