export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_INFORMATION_REQUEST = 'ORDER_INFORMATION_REQUEST';
export const ORDER_INFORMATION_SUCCESS = 'ORDER_INFORMATION_SUCCESS';
export const ORDER_INFORMATION_FAIL = 'ORDER_INFORMATION_FAIL';

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST';
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS';
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL';
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET';
