export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LIST_BRANDS_REQUEST = 'PRODUCT_LIST_BRANDS_REQUEST';
export const PRODUCT_LIST_BRANDS_SUCCESS = 'PRODUCT_LIST_BRANDS_SUCCESS';
export const PRODUCT_LIST_BRANDS_FAIL = 'PRODUCT_LIST_BRANDS_FAIL';

export const PRODUCT_LIST_CATEGORY_REQUEST = 'PRODUCT_LIST_CATEGORY_REQUEST';
export const PRODUCT_LIST_CATEGORY_SUCCESS = 'PRODUCT_LIST_CATEGORY_SUCCESS';
export const PRODUCT_LIST_CATEGORY_FAIL = 'PRODUCT_LIST_CATEGORY_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_REMOVE_REQUEST = 'PRODUCT_REMOVE_REQUEST';
export const PRODUCT_REMOVE_SUCCESS = 'PRODUCT_REMOVE_SUCCESS';
export const PRODUCT_REMOVE_FAIL = 'PRODUCT_REMOVE_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_BEST_RATED_REQUEST = 'PRODUCT_BEST_RATED_REQUEST';
export const PRODUCT_BEST_RATED_SUCCESS = 'PRODUCT_BEST_RATED_SUCCESS';
export const PRODUCT_BEST_RATED_FAIL = 'PRODUCT_BEST_RATED_FAIL';
export const PRODUCT_BEST_RATED_RESET = 'PRODUCT_BEST_RATED_RESET';

export const PRODUCT_LIST_BY_BRAND_REQUEST = 'PRODUCT_LIST_BY_BRAND_REQUEST';
export const PRODUCT_LIST_BY_BRAND_SUCCESS = 'PRODUCT_LIST_BY_BRAND_SUCCESS';
export const PRODUCT_LIST_BY_BRAND_FAIL = 'PRODUCT_LIST_BY_BRAND_FAIL';

export const PRODUCT_LIST_BY_CATEGORY_REQUEST = 'PRODUCT_LIST_BY_CATEGORY_REQUEST';
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS = 'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_LIST_BY_CATEGORY_FAIL = 'PRODUCT_LIST_BY_CATEGORY_FAIL';
